language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: twaclaw
  password:
    secure: JWskTbqQYjWhcpz3a28KTTvIS10GFkXY3/4Oht+qDDRgmNlKqPtj9gAWFodvc7/2Ar4C8epMp+4eYOye+bFYFxcnSzKeoniinArKTiA/bPNB5pD11P2bNcZL07gGw3UcuH/jiqUp+/WO5ApUvfAmBq6oqtbEBqTpRV3zZl2W9f/3A2TUTVpVrLFYZPdkxWpOh7OXhixCz2HvoUa/B9cYU9hngqYuhYLwZkIrq8XB8EimPrpIm6QpBJLfUi7b7qV5r3lOI381e9gGK/SLY4BDs2+nxMUWHuz3jnqthgIrJftgAlUzi1pEqgHUbBYFTenbIG3mECNNLTiQT9diEIs7ULI6eI0kfoBMwoXL9SNUW4yJ1eyqYerOdULa9QFfhOH8Ikegyi9Uvw1eGlHtOohVKYxTyl/0D8RvRzUZO+UgylfMLo8rc17QV/N5U/OazDaH0IGPo2rY91ZrMszwVa+pzjrjdTH0VLPJk9AlSbOZ1vcwaInTK+ljXVqyo3SxRZmA0Tu5K9VroEFblEC6aeG0jF9xDgjz+QkI9jNhmqZwXn9lJqUQQYeIyqs4l0yZGteuahbfiWuR0pN8iELgVi4BFhHZpRluCzvWtKgSTyzc0XcfJC895ecaBRA8QoRD16QT6ErkdoYyRAdzbt7g/aqShvLIzXioenfF6Wv2KVu1pFE=
  on:
    tags: true
    repo: twaclaw/remot3
    python: 3.6
